apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
    host: {{ include "unidle_key" . }}
    unidle-key: {{ include "unidle_key" . }}
    "mojanalytics.xyz/idleable": "true"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        "mojanalytics.xyz/idleable": "true"
    spec:
      priorityClassName: {{ .Chart.Name }}
      serviceAccountName: {{ .Values.Username }}-jupyter
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.jupyter.image }}:{{ .Values.jupyter.tag }}
          imagePullPolicy: {{ .Values.jupyter.imagePullPolicy }}
          ports:
            - name: jupyter
              containerPort: {{ .Values.jupyter.containerPort }}
          args:
            - "start-notebook.sh"
            - "--ContentsManager.allow_hidden=True"
            - "--ServerApp.token=''"
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "1"
          readinessProbe:
            httpGet:
              path: /
              port: jupyter
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: jupyter
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
          resources:
{{ toYaml .Values.jupyter.resources | indent 12 }}
